### PR TITLE
Compatibility with Rails 5.0

### PR DESCRIPTION
**Pull request by grosser**
rebasing @pschambacher s PR https://github.com/jamesarosen/arturo/pull/90 to see if it passes now ...

/fyi @jamesarosen

### CODE REVIEW

**Comment by grosser** [comment]
still 2 weird bugs left ...

**Comment by pschambacher** [comment]
Will have a look tomorrow morning.

**Comment by plukevdh** [comment]
Check out this one (two) weird bug that have Rails devs furious!

**Comment by plukevdh** [comment]
http://api.rubyonrails.org/classes/ActionController/Parameters.html#method-i-to_h

**Comment by plukevdh** [comment]
`to_h` vs `to_hash`

**Comment by pschambacher** [comment]
:shake_fist:

**Comment by plukevdh** [comment]
Somebody else had similar in the Airbrake gem. 

https://github.com/airbrake/airbrake/commit/01a2262f40610a7bb20581beb988ea29254d3e27

Unsure of where it's coming from tho. But it looks like `to_unsafe_h` is the one to use?

**Comment by pschambacher** [comment]
OK drop this PR, it's fixed in #90

**Pull request closed without merging**
